[project]
name = "agibot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "nonebot-adapter-console>=0.10.0",
    "nonebot-adapter-onebot>=2.4.6",
    "nonebot2[fastapi]>=2.5.0",
    "openai>=3.14.1",
    "openai-agents>=0.22.2",
    "playwright>=1.63.0",
    "trafilatura>=2.2.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.7",
]
